/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiExample: typeof import('./src/components/ApiExample.vue')['default']
    CategoryContextMenu: typeof import('./src/components/Category/CategoryContextMenu.vue')['default']
    CategoryItem: typeof import('./src/components/Category/CategoryItem.vue')['default']
    CategoryItemMenu: typeof import('./src/components/CategoryItemMenu.vue')['default']
    CategoryManager: typeof import('./src/components/Category/CategoryManager.vue')['default']
    CategoryTree: typeof import('./src/components/Category/CategoryTree.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    EditorText: typeof import('./src/components/EditorText.vue')['default']
    FixedColum: typeof import('./src/components/FixedColum.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NewNoteDialog: typeof import('./src/components/Notes/NewNoteDialog.vue')['default']
    NoteEditor: typeof import('./src/components/Notes/NoteEditor.vue')['default']
    NoteList: typeof import('./src/components/Notes/NoteList.vue')['default']
    OrderList: typeof import('primevue/orderlist')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLayout: typeof import('./src/components/SidebarLayout.vue')['default']
    SystemNavigation: typeof import('./src/components/SystemNavigation.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
